config/routes.rb
Blog::Application.routes.draw do

  match 'categories/:id' => "categories#show"
  match 'reviews/get_dishes' => "reviews#getDishes"
  match 'reviews/new' => 'reviews#new', :as => :new_review
  match 'restaurants/add' => 'restaurants#add', :as => :new_restaurant
  
  devise_scope :user do
    get 'logout', :to => 'devise/sessions#destroy'
    get 'login', :to => 'devise/sessions#new'
  end
  
  resources :dishes do
    resources :reviews
  end

  resources :categories do
    resources :restaurnants
  end

  resources :users
  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
 
  resources :restaurants do
    resources :reviews
    resources :dishes
  end
  

  
  
  root :to => "home#index"
  
  match '/contact', :to => 'pages#contact'
   match '/about',   :to => 'pages#about'
   match '/help',    :to => 'pages#help'
  get "home/index"
  devise_scope :user do
  get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
  
  match 'restaurants/:id/vote' => 'reviews#vote', :as => :review_vote
end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_many :reviews, :inverse_of => :dish
  belongs_to :restaurant, :inverse_of => :dishes
  validates :name, :price, :presence => true
  validates_uniqueness_of :name
  
  def to_s
    name.capitalize
  end
  
  def top_review
    self.reviews.all.sort_by{ |review| review.getScore }.reverse[0]
  end

  def recommend?
    return self.getAverageScore > 0.50 ? true: false
  end
  
  def getAverageScore
    self.reviews.all(:conditions => {:recommend => true}).length / self.reviews.all.length
  end
  
  def getAveragePrice
   (self.reviews.all.sum(&:price) ) / ( self.reviews.all.length)
  end
  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.xml
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.xml
  def show
    @dish = Dish.find(params[:id])
    @reviews = @dish.reviews.all.sort_by{ |review| review.getScore }.reverse
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.xml
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.xml
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to(@dish, :notice => 'Dish was successfully created.') }
        format.xml  { render :xml => @dish, :status => :created, :location => @dish }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.xml
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to(@dish, :notice => 'Dish was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.xml
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to(dishes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<tr id="<%= dish.id %>" style="cursor:pointer;" >

<td>
    <%= dish.name %>
</td>


 <td id="review_content_<%= dish.id %>" style="text-decoration:none;" title="<%=dish.top_review.content%>" onclick="window.location = '<%= restaurant_dish_url(@restaurant, dish) %>';">
	
	<div style="position:relative; left: 100px;">
		<!-- color: #18F -->
	<p class="bubble" style="position: absolute; color: #333;font-size: 11px; font-family: 'Century Gothic';">
	<% if dish.top_review.content.length > 100 %>
   <%= dish.content.to_s[0..100] %>...
	<% else %>
	 <%= dish.top_review.content %>
	<% end %>
	<br/><span style="color:#777777; font-size:9px;"> - <%= dish.top_review.reviewer %>
	</p>
	</div>
	<br/><span id="profile_image" style="position:relative; left: 5px; bottom:10px;"><%= image_tag "#{User.find_by_name(dish.top_review.reviewer).pic}", :alt => 'foo' %></span>

	
 </td>

<td style="text-align:right;">
	<% if dish.recommend? %>
	<%= image_tag "checkmark.png", :alt => 'fooz', :style => "position:relative; left: 26px; top:20px;" %>
	<% else %>
	
	<%= image_tag "x.png", :alt => 'foo', :style => "position:relative; left: 26px; top:20px;" %>
	<% end %>
	<b style="display:inline-block; position:relative; top: 35px; right:5px;"><%= dish.getAverageScore * 100 %>%</b>
</td>	
<td>
	<div style="font-size:20px; position:relative; top:23px; left: 0px;">
	<% review_price =  "$" * dish.getAveragePrice.to_i %>
	<%= review_price %>
	</div>
</td>
</tr>

<script>

</script>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pic %><br />
    <%= f.text_field :pic %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :restaurant %><br />
    <%= f.text_field :restaurant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pic</th>
    <th>Price</th>
    <th>Restaurant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= dish.pic %></td>
    <td><%= dish.price %></td>
    <td><%= dish.restaurant %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Review</h1>

	<% if user_signed_in? %>
	<%= render :partial => "reviews/form" %>
	<% else %>
	<br/>
	<div class="fberrorbox">Error: You must sign in via facebook login if you wish to post a review.</div> 
	
	<br/>
	<a style="text-decoration:none;" href="<%= user_omniauth_authorize_path(:facebook) %>"><div style="display:inline-block;"><%= image_tag "facebook_icon.png" %></div><div class="underline_hover" style="display:inline-block; position:relative; left:7px; bottom:5px;"> <h1> Sign in </h1></div></a>
	<% end %>
</div>


<%= link_to 'Back', root_path %>

app/views/dishes/show.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %>
<% end %>
<br/>



	<% content_for :three_column do %>

<div id="tabs">
	<ul id="navigation" style="border-color:white;">
		<li><a href="#tabs-1">Reviews</a></li>
		<li><a href="#tabs-2">Add a Review</a></li>
		<div class="restaurant_nav">
		<a class="restaurant_link" href="<%= restaurant_path(@dish.restaurant) %>"><%=@dish.restaurant %></a> >> <a class="restaurant_link" href="<%= dish_path(@dish) %>"><%= @dish %>
		</div>
	</ul>
	
<div class="cols two-cols">
	<div class="cl">&nbsp;</div>

	<div class="col col-last" id="tabs-1" style="width:93%;">
			<div class="ui-widget">Search: <input type="text"  size="30" id="dish_search" name="review[name]"></div>	
		<table border=true  class="flexigrid">
		<thead></thead>
		<tbody>	

<br/>	


<%= render :partial => "reviews/review", :collection => @dish.reviews %>


</tbody>
</table>
	</div>
	
	<div id="tabs-2">
		<h2 style="">Add a review:</h2>
		<% if user_signed_in? %>
		<%= render :partial => "reviews/form" %>
		<% else %>
		<br/>
		<div class="fberrorbox">Error: You must sign in via facebook login if you wish to post a review.</div> 
		
		<br/>
		<a style="text-decoration:none;" href="<%= user_omniauth_authorize_path(:facebook) %>"><div style="display:inline-block;"><%= image_tag "facebook_icon.png" %></div><div class="underline_hover" style="display:inline-block; position:relative; left:7px; bottom:5px;"> <h1> Sign in </h1></div></a>
		<% end %>
	</div>
		
	</div>
	<div class="cl">&nbsp;</div>
</div>
</div>
<% end %>


<script>


$(document).ready(function() 
    { 

			
		    $('input#dish_search').quicksearch('table.flexigrid tbody tr');
			


			$( "#tabs" ).tabs({
				cookie: {
					// store cookie for a day, without, it would be a session cookie
					expires: 1
				}
			});
						
       	$( ".flexigrid" ).flexigrid({
			colModel : [
			                        {display: 'Review', name : 'content', width : 500, sortable : true, align: 'left'},
			                        //{display: 'Reviewer', name : 'reviewer', width : 160, sortable : true, align: 'left'},
									{display: 'Recommend', name : 'recommend', width : 80, sortable : true, align: 'left'},
									{display: 'Price', name : 'price', width : 71, sortable : true, align: 'left'},
			 						{display: 'Helpful', name : 'helpful', width : 106, sortable : false, align: 'left'}
			                ],
		usepager: true,
		sortname: "",
		sortorder: "asc",
		title: '<%= @dish.name.titleize %>',
		useRp: true,
		rp: 15,
		showTableToggleBtn: true
		});
		
			$(".bDiv").css("height", "430px");
			

		        // Setup the tooltip with the content
		        $('a[id="dish"]').qtip(
		        {
		            content: thumbnail,
		            position: {
		                corner: {
		                    tooltip: 'leftMiddle'
		                   
		                }
		            },
		            style: {
		                tip: true, // Give it a speech bubble tip with automatic corner detection
		                name: 'blue'
		            }
		        });		
		
				<% @dish.reviews.each do |review| %>
				$("#review_content_<%=review.id%>").tipsy({gravity: $.fn.tipsy.autoNS});
				<% end %>
				$("[rel*=tipsy]").tipsy({gravity: $.fn.tipsy.autoNS});
				
		
    });


	
	$(function() {
			var availableTags = [];
				<% @dish.reviews.each do |reviews| %> 
				availableTags.push("<%= reviews.reviewer %>");
				<% end %>

			$( "#review_search, #review_name" ).autocomplete({
				source: availableTags
			});
		});

		
	</script>
	