config/routes.rb
Blog::Application.routes.draw do

  match 'categories/:id' => "categories#show"
  match 'reviews/get_dishes' => "reviews#getDishes"
  match 'reviews/new' => 'reviews#new', :as => :new_review
  match 'restaurants/add' => 'restaurants#add', :as => :new_restaurant
  
  devise_scope :user do
    get 'logout', :to => 'devise/sessions#destroy'
    get 'login', :to => 'devise/sessions#new'
  end
  
  resources :dishes do
    resources :reviews
  end

  resources :categories do
    resources :restaurnants
  end

  resources :users
  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
 
  resources :restaurants do
    resources :reviews
    resources :dishes
  end
  

  
  
  root :to => "home#index"
  
  match '/contact', :to => 'pages#contact'
   match '/about',   :to => 'pages#about'
   match '/help',    :to => 'pages#help'
  get "home/index"
  devise_scope :user do
  get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
  
  match 'restaurants/:id/vote' => 'reviews#vote', :as => :review_vote
end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :tags
  has_many :dishes, :inverse_of => :restaurant
  belongs_to :category, :inverse_of => :restaurants
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
  accepts_nested_attributes_for :dishes, :allow_destroy => :true,
       :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
       
  def to_s
    "#{self.name.titleize}"
  end
  
  def formatted_address
    "#{self.street}, #{self.city}, #{self.state}, #{self.zip}"
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.xml
  def index
    if params.has_key?("restaurant") && Restaurant.find_by_name(params["restaurant"]["name"])
      @restaurant = Restaurant.find_by_name(params["restaurant"]["name"])
      redirect_to restaurant_path(@restaurant)
      return
    else
      @restaurants = Restaurant.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @restaurants }
      end
    end
  end

  def restaurant_listing
    @restaurants = Restaurant.find_all_by_category_id(:category_id => @category)
  end
  
  # GET /restaurants/1
  # GET /restaurants/1.xml
  def show
    @restaurant = Restaurant.find(params[:id])
    @dishes = @restaurant.dishes.sort_by(&:name)
    @reviews = @restaurant.reviews.all.sort_by{ |review| review.getScore }.reverse
    @dish = Dish.new
    @review = Review.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  
  def add
    @restaurant = Restaurant.new
    if request.post?
      if !params[:restaurant][:name].blank? && !params[:restaurant][:street].blank? && !params[:restaurant][:city].blank? && !params[:restaurant][:state].blank? && !params[:restaurant][:zip].blank? && !params[:restaurant][:number].blank? && !params[:restaurant][:website].blank?
          @restaurant = Restaurant.new(params[:restaurant])
      else
        flash[:error] = 'One or more fields were left blank.'
        return
      end
      respond_to do |format|
        if @restuarant.save
          format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully created.') }
          format.xml  { render :xml => @restaurant, :status => :created, :location => @dish }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
        end
      end
    end
    
  end
  
  # GET /restaurants/new
  # GET /restaurants/new.xml
  def new
    @restaurant = Restaurant.new
    @category ||= Category.find(params[:category])
    @zip ||= params[:zip]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.xml
  def create
    if !params[:restaurant][:name].blank? && !params[:restaurant][:street].blank? && !params[:restaurant][:city].blank? && !params[:restaurant][:state].blank? && !params[:restaurant][:zip].blank? && !params[:restaurant][:number].blank? && !params[:restaurant][:website].blank?
        @restaurant = Restaurant.new(params[:restaurant])
    else
        @restaurant = Restaurant.new
        @zip = params[:zip][:to_s]
        @category = Category.find(params[:category][:id])
        flash[:error] = 'One or more fields were left blank.'
        render "new"
        return
    end
    
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully created.') }
        format.xml  { render :xml => @restaurant, :status => :created, :location => @restaurant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.xml
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.xml
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to(restaurants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

    def join_tags(restaurant)
      restaurant.tags.map { |t| t.name.strip }.join(", ")
    end
    
   

end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip, :value => @zip %>
  </div>
  <div class="field">
    <%= f.label "Picture URL" %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div> 
    <%= hidden_field(:category, :id) %>
    <%= hidden_field(:zip, :to_s) %>
<br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/add.html.erb
<% content_for :nav do %>
<%= get_navigation("add_rest") %>
<% end %>
<br/>

<h2>New Restaurant <span style="float:right;"><%= link_to 'Back', restaurants_path %></span></h2><br/>
<b style="color:red;"><%= flash[:error] %></b>
	<% if user_signed_in? %>
	<%= render 'form' %>
	<% else %>
<div class="fberrorbox">Error: You must sign in via facebook login if you wish to post a review.</div> 

	<br/>	<br/>

	<a style="text-decoration:none;" href="<%= user_omniauth_authorize_path(:facebook) %>"><div style="display:inline-block;"><%= image_tag "facebook_icon.png" %></div><div class="underline_hover" style="display:inline-block; position:relative; left:7px; bottom:5px;"> <h1> Sign in </h1></div></a>

	<br/>	<br/>
	<% end %>

app/views/restaurants/edit.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %>
<% end %>
<br/>

<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %>
<% end %>
	
<div class="cl">&nbsp;</div>
<div class="col">
<h2>Browse Restaurants</h2>
</div><br/>



<div class="ui-widget">Restaurant: <input type="text"  title="Search" size="30" id="restaurant_search" name="dish[name]"></div>	
<br/>
<table border=1 class="flexigrid">
<thead></thead>
<tbody >
<% @restaurants.each do |restaurant| %>
  <tr onclick="window.location = '<%= restaurant_url(restaurant) %>';" style="cursor:pointer;">
    <td><%= restaurant.name %></td>
    <td><%= restaurant.street %></td>
    <td><%= restaurant.city %></td>
    <td><%= restaurant.state %></td>
    <td><%= restaurant.zip %></td>
    <td><%= restaurant.number %></td>
  </tr>
<% end %>
</tbody >
</table>

<br />

<script>

$(document).ready(function() 
{
	
	
	$('input#restaurant_search').quicksearch('table.flexigrid tbody tr');
	
	$( ".flexigrid" ).flexigrid({
		colModel : [
		                        {display: 'Name', name : 'dish-id', width : 218, sortable : true, align: 'left'},
		                        {display: 'Street', name : 'content', width : 218, sortable : true, align: 'left'},
		                        {display: 'City', name : 'reviewer', width : 153, sortable : true, align: 'left'},
								{display: 'State', name : 'recommend', width : 30, sortable : true, align: 'left'},
								{display: 'Zip', name : 'price', width : 50, sortable : true, align: 'left'},
		 						{display: 'Number', name : '', width : 110, sortable : false, align: 'left'}
		                ],
	usepager: true,
	sortname: "",
	sortorder: "asc",
	title: 'Restaurants',
	useRp: true,
	rp: 15,
	showTableToggleBtn: true
	});
	$(".bDiv").css("height", "300px");
});	
</script>

app/views/restaurants/new.html.erb
<% content_for :nav do %>
<%= get_navigation("add_rest") %>
<% end %>
<br/>

<h2>New <%=@category %> Restaurant <span style="float:right;"><%= link_to 'Back', restaurants_path %></span></h2><br/>
<b style="color:red;"><%= flash[:error] %></b>
	<% if user_signed_in? %>
	<%= render 'form' %>
	<% else %>
<div class="fberrorbox">Error: You must sign in via facebook login if you wish to post a review.</div> 

	<br/>	<br/>

	<a style="text-decoration:none;" href="<%= user_omniauth_authorize_path(:facebook) %>"><div style="display:inline-block;"><%= image_tag "facebook_icon.png" %></div><div class="underline_hover" style="display:inline-block; position:relative; left:7px; bottom:5px;"> <h1> Sign in </h1></div></a>

	<br/>	<br/>
	<% end %>
	

app/views/restaurants/restaurant_listing.html.erb
Title: restaurant_listing

Main entry text

✂------✂------✂------✂------✂------✂------✂------✂------✂------✂------

Main entry continued

app/views/restaurants/show.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %>
<% end %>
<br/>



	<% content_for :three_column do %>

<div id="tabs">

	<ul id="navigation" style="border-color:white;">
		<li><a href="#tabs-1">About</a></li>
		<li><a href="#tabs-2">Dishes</a></li>
		<li><a href="#tabs-3">Reviews</a></li>
		<li><a href="#tabs-4">Add Review</a></li>
		<div class="restaurant_nav">
		<a class="restaurant_link" href="<%= restaurant_path(@restaurant) %>"><%=@restaurant %></a> 
		</div>
	</ul>
	
	
<div class="cols two-cols">
	<div class="cl">&nbsp;</div>
	<div class="col" id="tabs-1" style="height:275px;">
		
		
		
		<div class="infobox-container">
		<div class="triangle-l"></div>
		<div class="triangle-r"></div>
		<div class="infobox">
		<a id="dish"><h3><span><%= @restaurant %></span></h3></a>
		<p>&nbsp;</p>
		<p>
		  <b style="font-size:15px;">Address:</b>
		  <span style="font-size:13px;"><%= @restaurant.formatted_address %></span>
		  <br/>
		  <b style="font-size:15px;">Number:</b>
		  <span style="font-size:13px;"><%= @restaurant.number %></span>
		</p>
				<p>&nbsp;</p>
		
		</div>
		</div>
		
		<%= image_tag "http://maps.google.com/maps/api/staticmap?center=#{@restaurant.street.strip},#{@restaurant.city.strip},#{@restaurant.state.strip},#{@restaurant.zip.strip}&zoom=17&size=400x400&sensor=false&markers=#{@restaurant.street.strip},#{@restaurant.city.strip},#{@restaurant.state.strip},#{@restaurant.zip.strip}", :alt => 'foo', :style => "position:relative; left: 550px; bottom: 150px", :height => "250px;", :width => "250px;" %>
		
		<link href='http://fonts.googleapis.com/css?family=Playfair+Display&v1' rel='stylesheet' type='text/css'>
	
		<p id="notice"><%= notice %></p>
		
	</div>
	<div class="col col-last" id="tabs-2" style="width:93%;">
			<div class="ui-widget">Dish: <input type="text"  size="30" id="dish_search" name="dish[name]"></div>	
		<table border=true  class="flexigrid">
		<thead></thead>
		<tbody>	

<br/>	


<%= render :partial => "dishes/dish", :collection => @dishes %>


</tbody>
</table>
	</div>
	
	<div id="tabs-3">
		<h2>All Dish Reviews</h2><br/>
<div class="ui-widget">Search: <input type="text"  size="30" id="review_search" name="review[name]"></div>
<table border=true  class="flexi2">
<thead></thead>
<tbody>	

<br/>	

		<%= render :partial => "reviews/review", :collection => @reviews, :locals => { :dish_name => true }  %>
	</tbody>
	</table>		
	</div>
	
	<div id="tabs-4">
		<h2 style="">Add a review:</h2>
		<% if user_signed_in? %>
		<%= render :partial => "reviews/restaurants_review_form" %>
		<% else %>
		<br/>
		<div class="fberrorbox">Error: You must sign in via facebook login if you wish to post a review.</div> 
		
		<br/>
		<a style="text-decoration:none;" href="<%= user_omniauth_authorize_path(:facebook) %>"><div style="display:inline-block;"><%= image_tag "facebook_icon.png" %></div><div class="underline_hover" style="display:inline-block; position:relative; left:7px; bottom:5px;"> <h1> Sign in </h1></div></a>
		<% end %>
	</div>
	
	<div class="cl">&nbsp;</div>
</div>
</div>
<% end %>

	
<script>


$(document).ready(function() 
    { 
			
		
			$( "#tabs" ).tabs({
				cookie: {
					// store cookie for a day, without, it would be a session cookie
					expires: 10
				}
			});
			
		    $('input#dish_search').quicksearch('table.flexigrid tbody tr');
			


			
						
       	$( ".flexigrid" ).flexigrid({
			colModel : [
			                        {display: 'Dish', name : 'dish-id', width : 125, sortable : true, align: 'left'},
			                        {display: 'Top Review', name : 'content', width : 497, sortable : true, align: 'left'},
			                        //{display: 'Reviewer', name : 'reviewer', width : 160, sortable : true, align: 'left'},
									{display: 'Recommend', name : 'recommend', width : 85, sortable : true, align: 'left'},
									{display: 'Price', name : 'price', width : 47, sortable : true, align: 'left'},
			 						//{display: 'Helpful', name : 'helpful', width : 100, sortable : false, align: 'left'}
			                ],
		usepager: true,
		sortname: "",
		sortorder: "asc",
		title: 'Dishes',
		useRp: true,
		rp: 15,
		showTableToggleBtn: true
		});
		
		$( ".flexi2" ).flexigrid({
			colModel : [
									{display: 'Dish', name : 'dish-id', width : 110, sortable : true, align: 'left'},
			                        {display: 'Review', name : 'content', width : 375, sortable : true, align: 'left'},
									{display: 'Recommend', name : 'recommend', width : 80, sortable : true, align: 'left'},
									{display: 'Price', name : 'price', width : 71, sortable : true, align: 'left'},
			 						{display: 'Helpful', name : 'helpful', width : 112.3, sortable : false, align: 'left'}
			                ],
		usepager: true,
		sortname: "",
		sortorder: "asc",
		title: 'Reviews',
		useRp: true,
		rp: 15,
		showTableToggleBtn: true
		});

		
	    $('input#review_search').quicksearch('table.flexi2 tbody tr');			
		
		
		
		
			$(".bDiv").css("height", "430px");
			
		 thumbnail = $('<img />').attr({
		            src: '<%= @restaurant.website %>',
		            alt: 'Loading thumbnail...',
		            width: 202,
		            height: 152
		        });

		        // Setup the tooltip with the content
		        $('a[id="dish"]').qtip(
		        {
		            content: thumbnail,
		            position: {
		                corner: {
		                    tooltip: 'leftMiddle'
		                   
		                }
		            },
		            style: {
		                tip: true, // Give it a speech bubble tip with automatic corner detection
		                name: 'blue'
		            }
		        });		
		
				<% @dishes.each do |dish| %>
				$("#review_content_<%=dish.id%>").tipsy({gravity: $.fn.tipsy.autoNS});
				<% end %>
				$("[rel*=tipsy]").tipsy({gravity: $.fn.tipsy.autoNS});
		
    });


	
	$(function() {
			var availableTags = [];
				<% @dishes.each do |dish| %> 
				
				availableTags.push("<%= dish.name %>");
				<% end %>

			$( "#dish_search, #dish_name" ).autocomplete({
				source: availableTags
			});
		});

		
	</script>
	