config/routes.rb
Blog::Application.routes.draw do

  match 'categories/:id' => "categories#show"
  match 'reviews/get_dishes' => "reviews#getDishes"
  match 'reviews/new' => 'reviews#new', :as => :new_review
  match 'restaurants/add' => 'restaurants#add', :as => :new_restaurant
  
  devise_scope :user do
    get 'logout', :to => 'devise/sessions#destroy'
    get 'login', :to => 'devise/sessions#new'
  end
  
  resources :dishes do
    resources :reviews
  end

  resources :categories do
    resources :restaurnants
  end

  resources :users
  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
 
  resources :restaurants do
    resources :reviews
    resources :dishes
  end
  

  
  
  root :to => "home#index"
  
  match '/contact', :to => 'pages#contact'
   match '/about',   :to => 'pages#about'
   match '/help',    :to => 'pages#help'
  get "home/index"
  devise_scope :user do
  get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
  
  match 'restaurants/:id/vote' => 'reviews#vote', :as => :review_vote
end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants, :inverse_of => :category
  
  def to_s
    self.name
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all(:order => :name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
    @zip = params[:zip]
    consumer = OAuth::Consumer.new( Yelp::CONSUMER_KEY,Yelp::SECRET, {:site => "http://api.yelp.com", :signature_method => "HMAC-SHA1", :scheme => :query_string})
    access_token = OAuth::AccessToken.new( consumer, Yelp::TOKEN, Yelp::TOKEN_SECRET)
    url = "/v2/search?location=#{@zip}&category_filter=#{@category.category_filter}"
    data = access_token.get(url).body
    data = JSON.parse(data) 
    if data['code'] == '/api/status/error'
      raise "web service error #{url}"
    end
    data = data["businesses"]
    if !data.nil?
    #------------------ START FETCHING INFORMATION ------------ #
    data.each do |datum|
      attrs = {:name => datum["name"], :street => datum["location"]["address"][0], :city => datum["location"]["city"], :state => datum["location"]["state_code"], :zip => datum["location"]["postal_code"], :number => datum["display_phone"] , :website => datum["image_url"]}
      if Restaurant.first(:conditions => attrs).nil?
        new_rest = Restaurant.create(attrs)
        new_rest.category = @category
        new_rest.save
      end
    end
    #------------------ END FETCHING INFORMATION ------------ #
    else 
    end
    @restaurants = @category.restaurants.sort_by(&:name)
  end

  def restaurant_listing
     @category = Category.find_by_name(params[:name])
     @restaurants = Restaurant.find_by_category_id(@category)
  end
  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
   

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %> 
<% end %>
	
<div class="cl">&nbsp;</div>
<div class="col">
<br/>
<h2>Browse Categories</h2>
</div><br/>



<div class="ui-widget">
<b>Category:</b> <input type="text"  title="Search" size="30" id="category_search">
<span style="position:relative; left:204px;"><b>Zipcode:</b> <input type="text"  size="30" id="zipcode_search" name="city[name]"></span></div>	
<br/>
<table border=1 class="flexigrid">
<thead></thead>
<tbody >
<% @categories.each do |category| %>

  <tr onclick="showCategory('<%= category_path(category) %>')" style="cursor:pointer;">
    <td><%= category.name %></td>
  </tr>
<% end %>

<script>
function showCategory(cat_url)
{
	var zipcode = $("#zipcode_search").val();
	var url = cat_url + "/?zip=" + zipcode;
	window.location = url;
}
</script>
</tbody >
</table>

<br />




<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
<script type="text/javascript"> 
  var geocoder;

  if (navigator.geolocation ) {
	initialize();
    navigator.geolocation.getCurrentPosition(successFunction, handle_errors);
}
else
{  
 	yqlgeo.get('visitor', normalize_yql_response);  
}
//Get latitude and longitude;
function successFunction(position) {
    var lat = position.coords.latitude;
    var lng = position.coords.longitude;
    codeLatLng(lat, lng)
}

function normalize_yql_response(response)  
{  
    if (response.error)  
    {  
        var error = { code : 0 };  
        handle_error(error);  
        return;  
    }  

    var position = {  
        coords :  
        {  
            latitude: response.place.centroid.latitude,  
            longitude: response.place.centroid.longitude  
        },  
        address :  
        {  
            city: response.place.locality2.content,  
            region: response.place.admin1.content,  
            country: response.place.country.content  
        }  
    };  

    handle_geolocation_query(position);  
}
function handle_errors(error)  
{  
    switch(error.code)  
    {  
        case error.PERMISSION_DENIED: alert("user did not share geolocation data");  
        break;  

        case error.POSITION_UNAVAILABLE: alert("could not detect current position");  
        break;  

        case error.TIMEOUT: alert("retrieving position timedout");  
        break;  

        default: alert("unknown error");  
        break;  
    }  
}


  function initialize() {
    geocoder = new google.maps.Geocoder();
  }

  function codeLatLng(lat, lng) {
	var loc, local;
    var latlng = new google.maps.LatLng(lat, lng);
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
      console.log(results)
        if (results[1]) 
		{
         //formatted address
         local = results[0].address_components[7].short_name;
        //find country name
             for (var i=0; i<results[0].address_components.length; i++) {
            for (var b=0;b<results[0].address_components[i].types.length;b++) {

            //there are different types that might hold a city admin_area_lvl_1 usually does in come cases looking for sublocality type will be more appropriate
				if(results[0].address_components[i].short_name.length == 5 && results[0].address_components[i].short_name.match(/\d{5}/) != null)
				{
					local = results[0].address_components[i].short_name;
				}
              
            }
        }

	 	$("#zipcode_search").val(local);

        } else {
          alert("No results found");
        }
      } else {
        alert("Geocoder failed due to: " + status);
      }
    });
  }
$(document).ready(function() 
{

	var cats = [];
	<% Category.all.each do |category| %> 
	cats.push("<%= category.name %>");
	<% end %>

	$( '#category_search' ).autocomplete({
	source: cats
	});

	$('input#category_search').quicksearch('table.flexigrid tbody tr');
	
	$( ".flexigrid" ).flexigrid({
		colModel : [
		                        {display: 'Name', name : 'dish-id', width : 842, sortable : true, align: 'left'}
		                ],
	usepager: true,
	sortname: "",
	sortorder: "asc",
	title: 'Categories',
	useRp: true,
	rp: 15,
	showTableToggleBtn: true
	});
	$(".bDiv").css("height", "330px");
});	
</script>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for :nav do %>
<%= get_navigation("browse") %>
<% end %>
	
<div class="cl">&nbsp;</div>
<div class="col">
<br/>
<h2>Browse <%= @category %>  Restaurants</h2>
</div><br/>


<div class="ui-widget">
Restaurant: <input type="text"  title="Search" size="30" id="restaurant_search" name="dish[name]">
<div style="float:right;" class="new_restaurant"> <%= link_to 'New Restaurant', new_restaurant_path(:category => @category, :zip => @zip), :style => "text-decoration:none; 1px solid #f2f2f2;" %> </div>
</div>


<br/>
<table border=1 class="flexigrid">
<thead></thead>
<tbody >
<% @restaurants.each do |restaurant| %>

  <tr onclick="window.location = '<%= restaurant_url(restaurant) %>';" style="cursor:pointer;">
    <td><%= restaurant.name %></td>
    <td><%= restaurant.street %></td>
    <td><%= restaurant.city %></td>
    <td><%= restaurant.state %></td>
    <td><%= restaurant.zip %></td>
    <td><%= restaurant.number %></td>
  </tr>
<% end %>
</tbody >
</table>

<br />




<script>

$(document).ready(function() 
{
	
	$("#new_restaurant").hover(function()
	{
		$(this).css("color", "#45C7EE");
		$(this).css("text-decoration", "underline");
	},
	function()
	{
		$(this).css("text-decoration", "none");		
	});
	
	$('input#restaurant_search').quicksearch('table.flexigrid tbody tr');
	
	$( ".flexigrid" ).flexigrid({
		colModel : [
		                        {display: 'Name', name : 'dish-id', width : 218, sortable : true, align: 'left'},
		                        {display: 'Street', name : 'content', width : 218, sortable : true, align: 'left'},
		                        {display: 'City', name : 'reviewer', width : 153, sortable : true, align: 'left'},
								{display: 'State', name : 'recommend', width : 30, sortable : true, align: 'left'},
								{display: 'Zip', name : 'price', width : 50, sortable : true, align: 'left'},
		 						{display: 'Number', name : 'number', width : 110, sortable : false, align: 'left'}
		                ],
	usepager: true,
	sortname: "",
	sortorder: "asc",
	title: 'Restaurants',
	useRp: true,
	rp: 15,
	showTableToggleBtn: true
	});
	$(".bDiv").css("height", "300px");
});	
</script>